# Generated by Django 4.0.4 on 2022-04-13 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('boardapp', '0002_rename_comment_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='liked',
            field=models.ManyToManyField(through='boardapp.PostUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postuser',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boardapp.post'),
        ),
        migrations.AddField(
            model_name='postuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
