# Generated by Django 4.0.4 on 2022-04-20 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0013_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
    ]
